spring:
    config:
        import: optional:configserver:http://localhost:8000
    application:
        name: Api-Gateway
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    main:
        web-application-type: reactive
