spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        -id: AuthService
        uri: lb:http://AuthService
        predicates:
          - Path=/authenticate/**
        -id: PropertyService
        uri: lb:http://PropertyService
        predicates:
          - Path=/property/**
        -id: Reservation_Service
        uri: lb:http://Reservation_Service
        predicates:
          - Path=/reservation/**

server:
  port: 8222